{
  "formatVersion": "1.1",
  "component": {
    "group": "org.endlesssource.mediainterface",
    "module": "macos",
    "version": "26.2.7-dev-java-8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.endlesssource.mediainterface",
          "module": "core",
          "version": {
            "requires": "26.2.7-dev-java-8"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.2.7-dev-java-8.jar",
          "url": "macos-26.2.7-dev-java-8.jar",
          "size": 228982,
          "sha512": "3dd8cf2b6f5cbbd332a284aedb2cac09ea4b009a8c1897b4cf5e1170b43dec46d61f47435b472aeeb9a59cb02414f59799a3c95009820fa9cf0c87b8f2b44f45",
          "sha256": "f6174f4fc2542cd6d5290e43bbfab9cf4f55068988161aa7d29ff50c557d8ce7",
          "sha1": "87e726c9f8ddfabad534f1a96c37c63098fb1923",
          "md5": "d69c0d887536100d97cace98c2bfed87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "core",
          "version": {
            "requires": "26.2.7-dev-java-8"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.2.7-dev-java-8.jar",
          "url": "macos-26.2.7-dev-java-8.jar",
          "size": 228982,
          "sha512": "3dd8cf2b6f5cbbd332a284aedb2cac09ea4b009a8c1897b4cf5e1170b43dec46d61f47435b472aeeb9a59cb02414f59799a3c95009820fa9cf0c87b8f2b44f45",
          "sha256": "f6174f4fc2542cd6d5290e43bbfab9cf4f55068988161aa7d29ff50c557d8ce7",
          "sha1": "87e726c9f8ddfabad534f1a96c37c63098fb1923",
          "md5": "d69c0d887536100d97cace98c2bfed87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.2.7-dev-java-8-sources.jar",
          "url": "macos-26.2.7-dev-java-8-sources.jar",
          "size": 215606,
          "sha512": "9333269c3cc37b3043c214737b920d908b551d1e9e2bff39855cb919cd3892ea2d0465e754fc4be61edacbfcb4d56397966c39438db7bb79dad6260cce2ce8f8",
          "sha256": "6f4fade1cd458a9ed9daef131c445c008057ed1dc390c18bb5003a057213651b",
          "sha1": "32179bb7b2925b9633e192353830b3d41a111e76",
          "md5": "01cd4bd380e442ea27f70317274920c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.2.7-dev-java-8-javadoc.jar",
          "url": "macos-26.2.7-dev-java-8-javadoc.jar",
          "size": 80911,
          "sha512": "720c27d79a20bb71f63d8508fab84b465d1a1af857d44fd11ee62500ec451bc8c62406969cb71c7676cb4c2bcad9cdc6164fbd05afa0ce344958d9abc019f5ea",
          "sha256": "b695e7f63bc79d3d5dccd11a34032eefe181d676df5efc5c8bde652b92ed8ce1",
          "sha1": "ea031fe2d46161e9a8fc880bc1bc41058251d912",
          "md5": "b7629c267dd1d63ac02a35a9ab71caed"
        }
      ]
    }
  ]
}
