{
  "formatVersion": "1.1",
  "component": {
    "group": "org.endlesssource.mediainterface",
    "module": "core",
    "version": "26.2.7-dev-java-8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-26.2.7-dev-java-8.jar",
          "url": "core-26.2.7-dev-java-8.jar",
          "size": 14355,
          "sha512": "36d713bef8c59d74f4c375ce31b60a6b43d49aadbc75c961117c2ac5af8461e30c750ffd2ec825c673196050dd18e3405728983de7cc836ebf1ca70c9ee587b3",
          "sha256": "d38715ec2656591cc81406e353fc7c699e48a0941a726b7f7ad59921bb40384d",
          "sha1": "6c60a87b4d11206056327262d0d510ead227d2c1",
          "md5": "e5b91a98b8cdaeaeb29a93aa4e324eae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-26.2.7-dev-java-8.jar",
          "url": "core-26.2.7-dev-java-8.jar",
          "size": 14355,
          "sha512": "36d713bef8c59d74f4c375ce31b60a6b43d49aadbc75c961117c2ac5af8461e30c750ffd2ec825c673196050dd18e3405728983de7cc836ebf1ca70c9ee587b3",
          "sha256": "d38715ec2656591cc81406e353fc7c699e48a0941a726b7f7ad59921bb40384d",
          "sha1": "6c60a87b4d11206056327262d0d510ead227d2c1",
          "md5": "e5b91a98b8cdaeaeb29a93aa4e324eae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-26.2.7-dev-java-8-sources.jar",
          "url": "core-26.2.7-dev-java-8-sources.jar",
          "size": 10349,
          "sha512": "fe6bbb491d40c9d4064a08488bc0420d4d3e2dcfd268488c4a82baf544857b8a0b3a9c29c34fb82cca13b252c967bcf6eea076b94b7653515232970f41f7ea84",
          "sha256": "f25a55126fa8c68661aed35171fd61167d8409840bc69e65346c8714b7ed19ed",
          "sha1": "38eafd143c99d42e0594b040ae2cfe5e23c4471c",
          "md5": "413836685f7b6366dc7395ba0c21d695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-26.2.7-dev-java-8-javadoc.jar",
          "url": "core-26.2.7-dev-java-8-javadoc.jar",
          "size": 125330,
          "sha512": "d8e4331d442d08dab5daf66157e9d5fbb90feb5ab0093d21abb308894de778b3e2ca7c50f3bd420fa001bfa856ec6e14bfa4630a1eed3797c2f326f41cf0a32e",
          "sha256": "18197b83eb3dec9fa813edfd0822982541021af8452b47f1207e276d428e6645",
          "sha1": "fdc78e36f3d612e99b52bafefc0b048a8fb04437",
          "md5": "9d32abc5970546e38df84c08df5843b6"
        }
      ]
    }
  ]
}
