{
  "formatVersion": "1.1",
  "component": {
    "group": "org.endlesssource.mediainterface",
    "module": "all",
    "version": "26.2.6-dev-java-8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.endlesssource.mediainterface",
          "module": "core",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "linux",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "windows",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "macos",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "core",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "linux",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "windows",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        },
        {
          "group": "org.endlesssource.mediainterface",
          "module": "macos",
          "version": {
            "requires": "26.2.6-dev-java-8"
          }
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "all-26.2.6-dev-java-8-sources.jar",
          "url": "all-26.2.6-dev-java-8-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "all-26.2.6-dev-java-8-javadoc.jar",
          "url": "all-26.2.6-dev-java-8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "all-26.2.6-dev-java-8.jar",
          "url": "all-26.2.6-dev-java-8.jar",
          "size": 5263304,
          "sha512": "2d1ddad99ea25884ce33ae0875efc1d9313a1be32c147ac4d258ac01b8b65069806bcb0fc3d9d10eaaa81d4d034e7e651329592393bb335918e76508bd11b932",
          "sha256": "39a34367e097cf26d5f6aebfda934d905d9c0b45d31502e59f1572e5bae0198f",
          "sha1": "573a60282ee4dbf958c7f602dbe266e8881d99f3",
          "md5": "84411e94d715dbe734bc38c58bb8b7a5"
        }
      ]
    }
  ]
}
